# Generated by Django 3.1.7 on 2021-04-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaynote',
            name='created_on',
            field=models.DateField(),
        ),
    ]
