# Generated by Django 3.1.7 on 2021-04-10 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20210408_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaynote',
            name='emotions',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
